# Generated by Django 6.0.8 on 2026-08-05 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.BigAutoField(db_column='employee_id', primary_key=True, serialize=False)),
                ('organization_id', models.BigIntegerField(db_column='organization_id', default=1)),
                ('employee_code', models.CharField(db_column='employee_code', max_length=50, unique=True)),
                ('employee_name', models.CharField(db_column='employee_name', max_length=255)),
                ('designation', models.CharField(db_column='designation', max_length=100)),
                ('department', models.CharField(db_column='department', max_length=100)),
                ('email', models.EmailField(db_column='email', max_length=255, unique=True)),
                ('mobile_number', models.CharField(db_column='mobile_number', max_length=20, unique=True)),
                ('status', models.CharField(db_column='status', default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.BigAutoField(db_column='organization_id', primary_key=True, serialize=False)),
                ('organization_code', models.CharField(db_column='organization_code', max_length=50, unique=True)),
                ('organization_name', models.CharField(db_column='organization_name', max_length=255)),
                ('organization_type', models.CharField(blank=True, db_column='organization_type', max_length=100, null=True)),
                ('address', models.TextField(blank=True, db_column='address', null=True)),
                ('city', models.CharField(blank=True, db_column='city', max_length=100, null=True)),
                ('state', models.CharField(blank=True, db_column='state', max_length=100, null=True)),
                ('country', models.CharField(blank=True, db_column='country', max_length=100, null=True)),
                ('contact_person', models.CharField(blank=True, db_column='contact_person', max_length=255, null=True)),
                ('contact_email', models.CharField(blank=True, db_column='contact_email', max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, db_column='contact_phone', max_length=50, null=True)),
                ('status', models.CharField(db_column='status', default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organization',
            },
        ),
        migrations.CreateModel(
            name='OTPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_column='identifier', max_length=255)),
                ('otp_code', models.CharField(db_column='otp_code', max_length=6)),
                ('purpose', models.CharField(choices=[('FORGOT_PASSWORD', 'Forgot Password'), ('FORGOT_USERNAME', 'Forgot Username'), ('LOGIN_OTP', 'Login OTP')], db_column='purpose', max_length=50)),
                ('expires_at', models.DateTimeField(db_column='expires_at')),
                ('is_used', models.BooleanField(db_column='is_used', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'verbose_name': 'OTP Record',
                'verbose_name_plural': 'OTP Records',
                'db_table': 'otp_record',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.BigAutoField(db_column='role_id', primary_key=True, serialize=False)),
                ('role_name', models.CharField(db_column='role_name', max_length=100)),
                ('role_description', models.TextField(blank=True, db_column='role_description', null=True)),
                ('status', models.CharField(db_column='status', default='ACTIVE', max_length=20)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='ApplicationUser',
            fields=[
                ('user_id', models.BigAutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('role_id', models.BigIntegerField(db_column='role_id', default=1)),
                ('username', models.CharField(db_column='username', max_length=150, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', null=True)),
                ('account_status', models.CharField(db_column='account_status', default='ACTIVE', max_length=20)),
                ('employee', models.ForeignKey(blank=True, db_column='employee_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_users', to='LT_AMS_API.employee')),
            ],
            options={
                'verbose_name': 'Application User',
                'verbose_name_plural': 'Application Users',
                'db_table': 'application_user',
            },
        ),
    ]
