# Generated by Django 6.0.8 on 2026-08-18 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LT_AMS_API', '0003_seed_demo_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(db_column='date', default=datetime.date.today),
        ),
    ]
