# Generated by Django 6.0.8 on 2026-09-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LT_AMS_API', '0004_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, db_column='address', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(blank=True, db_column='city', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='country',
            field=models.CharField(blank=True, db_column='country', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='pincode',
            field=models.CharField(blank=True, db_column='pincode', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='state',
            field=models.CharField(blank=True, db_column='state', max_length=100, null=True),
        ),
    ]
