"""
Django settings for lt_be_v1 project.

Generated by 'django-admin startproject' using Django 6.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-1p2al4x$=q5v$i%yhjfgz1cja@9a7_!#i5@3nwkmeb!tv!7gs-')
DEBUG = os.getenv('DEBUG', 'True') == 'True'
allowed_hosts_env = os.getenv('ALLOWED_HOSTS', 'localhost:5173, 10.1.150.142:3000, localhost, 10.1.150.142, 127.0.0.1')
if allowed_hosts_env:
    if allowed_hosts_env.strip().startswith('[') and allowed_hosts_env.strip().endswith(']'):
        import ast
        try:
            ALLOWED_HOSTS = ast.literal_eval(allowed_hosts_env.strip())
        except Exception:
            ALLOWED_HOSTS = [h.strip(" '\"[]") for h in allowed_hosts_env.split(',') if h.strip(" '\"[]")]
    else:
        ALLOWED_HOSTS = [h.strip() for h in allowed_hosts_env.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = ['localhost:5173', '10.1.150.142:3000', 'localhost', '10.1.150.142', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    'corsheaders',
    'channels',
    'LT_AMS_API.apps.LtAmsApiConfig',
    'apps.logs.apps.LogsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'allow_cidr.middleware.AllowCIDRMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lt_be_v1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lt_be_v1.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'


# Custom User Model
AUTH_USER_MODEL = 'LT_AMS_API.ApplicationUser'


# Database Setup (Local vs Server PostgreSQL)
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_ENV = os.getenv('DB_ENVIRONMENT', 'local').lower()

if 'test' in sys.argv or os.getenv('USE_SQLITE', 'False').lower() == 'true' or DB_ENV in ['sqlite', 'sqlite3']:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # Select environment settings based on DB_ENVIRONMENT variable
    if DB_ENV == 'server':
        db_name = os.getenv('SERVER_DB_NAME')
        db_user = os.getenv('SERVER_DB_USER')
        db_password = os.getenv('SERVER_DB_PASSWORD')
        db_host = os.getenv('SERVER_DB_HOST')
        db_port = os.getenv('SERVER_DB_PORT')
    else:
        # Default to local database configuration
        db_name = os.getenv('LOCAL_DB_NAME')
        db_user = os.getenv('LOCAL_DB_USER')
        db_password = os.getenv('LOCAL_DB_PASSWORD')
        db_host = os.getenv('LOCAL_DB_HOST')
        db_port = os.getenv('LOCAL_DB_PORT')

    db_engine = os.getenv('DB_ENGINE', 'django.db.backends.postgresql')
    conn_max_age = int(os.getenv('DB_CONN_MAX_AGE', '0'))

    db_options = {}
    if 'postgresql' in db_engine:
        # Prevent ASGI worker hangs on DB timeouts (fail fast in 5 seconds)
        db_options = {
            'connect_timeout': int(os.getenv('DB_CONNECT_TIMEOUT', '5')),
        }

    DATABASES = {
        'default': {
            'ENGINE': db_engine,
            'NAME': db_name,
            'USER': db_user,
            'PASSWORD': db_password,
            'HOST': db_host,
            'PORT': db_port,
            'CONN_MAX_AGE': conn_max_age,
            'OPTIONS': db_options,
        }
    }


# Redis & Channel Layer Configuration
REDIS_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0')

if 'test' in sys.argv:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
            },
        },
    }

# Celery Configuration
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Django REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Simple JWT Configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(minutes=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'user_id',
    'USER_ID_CLAIM': 'user_id',
}


# Swagger / OpenAPI Settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Siteaense Application API Services',
    'DESCRIPTION': 'REST API services for Authentication, Employee Management, and Access Control',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
}

# Security & Host Configuration
# Default DEBUG to True in local development, False in server/production
DEBUG = os.getenv('DEBUG', 'True' if os.getenv('DB_ENVIRONMENT', 'local').lower() in ('local', 'sqlite', 'sqlite3') else 'False').lower() in ('true', '1', 't')

# Parse ALLOWED_HOSTS dynamically from environment with robust defaults
_env_allowed_hosts = os.getenv('ALLOWED_HOSTS')
if _env_allowed_hosts:
    ALLOWED_HOSTS = [h.strip() for h in _env_allowed_hosts.split(',') if h.strip()]
else:
    ALLOWED_HOSTS = [
        "siteaense.kct.ac.in",
        "sitesense.kct.ac.in",
        "103.196.28.198",
        "10.1.150.142",
        "10.1.68.42",
        "10.1.68.45",
        "10.1.82.235",
        "localhost",
        "127.0.0.1",
        "backend",
        "lt_ams_backend",
        "testserver",
    ]

# Tell Django it is operating behind Cloudflare/Nginx HTTPS Reverse Proxy
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

ALLOWED_CIDR_NETS = [
    '10.1.82.0/24',
    '10.1.68.0/24',
    '10.1.150.0/24',
    '172.16.0.0/12',
    '192.168.0.0/16',
]

# CSRF & CORS Whitelist (Parsed from env with robust defaults)
_env_csrf = os.getenv('CSRF_TRUSTED_ORIGINS')
if _env_csrf:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _env_csrf.split(',') if o.strip()]
else:
    CSRF_TRUSTED_ORIGINS = [
        "https://siteaense.kct.ac.in",
        "https://sitesense.kct.ac.in",
        "http://siteaense.kct.ac.in",
        "http://103.196.28.198",
        "http://103.196.28.198:3000",
        "http://10.1.150.142",
        "http://10.1.150.142:3000",
        "http://10.1.82.235",
        "http://10.1.82.235:3000",
        "http://localhost:3000",
        "http://localhost:5173",
        "http://127.0.0.1:3000",
        "http://127.0.0.1:5173",
        "capacitor://localhost",
        "http://localhost",
    ]

_env_cors = os.getenv('CORS_ALLOWED_ORIGINS')
if _env_cors:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _env_cors.split(',') if o.strip()]
else:
    CORS_ALLOWED_ORIGINS = [
        "https://siteaense.kct.ac.in",
        "https://sitesense.kct.ac.in",
        "http://siteaense.kct.ac.in",
        "capacitor://localhost",
        "http://localhost",
        "https://localhost",
        "http://103.196.28.198",
        "http://103.196.28.198:3000",
        "http://10.1.150.142",
        "http://10.1.150.142:3000",
        "http://10.1.82.235:3000",
        "http://localhost:3000",
        "http://localhost:5173",
        "http://127.0.0.1:3000",
        "http://127.0.0.1:5173",
    ]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Production Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} [{levelname}] [{name}] {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'null': {
            'class': 'logging.NullHandler',
        },
    },
    'loggers': {
        'django.security.DisallowedHost': {
            'handlers': ['null'],
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}