# Generated by Django 6.0.8 on 2026-08-26 06:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LT_AMS_API', '0004_alter_attendance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('log_id', models.BigAutoField(db_column='log_id', primary_key=True, serialize=False)),
                ('detection_type', models.CharField(db_column='detection_type', db_index=True, max_length=100)),
                ('confidence', models.FloatField(db_column='confidence', default=0.0)),
                ('bbox', models.JSONField(blank=True, db_column='bbox', null=True)),
                ('snapshot', models.TextField(blank=True, db_column='snapshot', null=True)),
                ('severity', models.CharField(db_column='severity', default='MEDIUM', max_length=20)),
                ('is_alert', models.BooleanField(db_column='is_alert', db_index=True, default=False)),
                ('timestamp', models.DateTimeField(db_column='timestamp', db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('camera', models.ForeignKey(blank=True, db_column='camera_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_logs', to='LT_AMS_API.camera')),
                ('site', models.ForeignKey(blank=True, db_column='site_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detection_logs', to='LT_AMS_API.site')),
            ],
            options={
                'verbose_name': 'Detection Log',
                'verbose_name_plural': 'Detection Logs',
                'db_table': 'detection_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
