name: Deploy Django Backend to Production Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy Docker Container
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Docker Container
        run: |
          cd ~/lt-be-v1 || exit 1
          git pull origin main
          docker compose down
          docker compose up -d --build
          docker image prune -f
